[tool.poetry]
name = "vespa-plugin"
version = "0.1.0"
description = ""
authors = ["Simon Lee <simon2020291@gmail.com>"]
readme = "README.md"
packages = [{include = "vespa_plugin"}]

[tool.poetry.dependencies]
python = "~3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
